<?php

/**
 * @return array $items Array asociativo cuyas claves son las rutas y los valores son las propiedades de cada ruta
 */
function hola_mundo_menu() {
    $items['test/hello'] = array(
        'title' => 'Hola Mundo',
        'page callback' => 'hola_mundo',
        'access callback' => TRUE,
    );

    return $items;
}

/**
 * @return string
 */
function hola_mundo() {
   return "Hola mundo";
}